package fxTyoaika.model.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxTyoaika.model.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.17 22:27:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UserListTest {



  // Generated by ComTest BEGIN
  /** testUserList11 */
  @Test
  public void testUserList11() {    // UserList: 11
    UserList lista = new UserList(5); 
    assertEquals("From: UserList line: 13", 0, lista.size()); 
    assertEquals("From: UserList line: 14", true, lista.isEmpty()); 
    User user1 = new User(1, "Janne"); 
    User user2 = new User(2, "Jonne"); 
    User user3 = new User(3, "Jenni"); 
    lista.add(user1); 
    lista.add(user2); 
    lista.add(user3);  //[Janne, Jonne, Jenni]
    assertEquals("From: UserList line: 23", 3, lista.size()); 
    assertEquals("From: UserList line: 24", false, lista.isEmpty()); 
    User user4 = new User(4, "Joonas"); 
    lista.add(0, user4);  //[Joonas, Janne, Jonne, Jenni]
    assertEquals("From: UserList line: 28", 0, lista.indexOf(user4)); 
    assertEquals("From: UserList line: 29", true, lista.contains(user4)); 
    assertEquals("From: UserList line: 31", true, lista.remove(user4));  // [Janne, Jonne, Jenni]
    lista.remove(1);  // [Janne, Jenni]
    assertEquals("From: UserList line: 33", true, lista.get(1).equals(user3)); 
    User user5 = new User(5, "Jammu"); 
    User user6 = new User(6, "Kyösti"); 
    assertEquals("From: UserList line: 38", false, lista.contains(user5)); 
    assertEquals("From: UserList line: 39", -1, lista.indexOf(user6)); 
    lista.add(user5); 
    lista.add(user6);  //[Janne, Jenni, Jammu, Kyösti]
    assertEquals("From: UserList line: 44", 4, lista.size()); 
    lista.add(user4);  //[Janne, Jenni, Jammu, Kyösti, Joonas]
    lista.add(0, user2);  //[Jonne, Janne, Jenni, Jammu, Kyösti, Joonas]
    assertEquals("From: UserList line: 49", 6, lista.size()); 
    User user7 = new User(7, "Jorma"); 
    lista.set(4, user7); 
    assertEquals("From: UserList line: 54", false, lista.contains(user6)); 
    lista.get(1).equals(user1); 
  } // Generated by ComTest END
}